<?php

/**
 * @file
 * Functions to support theming in the Suchi theme.
 */


function suchi_preprocess_paragraph(&$variables) {
  //echo "<pre>2: "; print_r( $variables['paragraph']);
  //echo "<pre>"; print_r($variables['content']['field_embed_code']); die;
  $variables['field_embed_code'] = $variables['elements']['field_embed_code'];
  $variables['field_link'] = $variables['elements']['field_link'];
}