<?php

/**
 * @file
 *
 * This file is the module file which contains the hook_cron for queuing.
 */

use Drupal\Core\Entity\EntityInterface;
use Drupal\Core\Queue\QueueFactory;
use Drupal\Core\Queue\QueueInterface;

/**
 * Implements hook_entity_insert().
 */
function suchi_queues_entity_insert(EntityInterface $entity) {
  if ($entity->getEntityTypeId() !== 'user') {
    return;
  }

  /** @var QueueFactory $queue_factory */
  $queue_factory = \Drupal::service('queue');
  /** @var QueueInterface $queue */
  $queue = $queue_factory->get('cron_user_mail');
  $item = new \stdClass();
  $item->uid = $entity->id();
  $queue->createItem($item);
}

/**
 * Implements hook_cron().
 */
function suchi_queues_cron() {


}

/**
 * Implements hook_mail().
 */
function suchi_queues_mail($key, &$message, $params) {
  $variables = $params['account'];
  $username[] = $variables->name->value;
  $options['langcode'] = $message['langcode'];
  switch($key) {
    case 'notice':
      $message['subject'] = t('Notification from D8 Exercises');
      $message['body'][] = t("Dear @username\n\nWelcome to this site.", $username, $options);
      break;
  }
}