<?php

/**
 * @file
 *
 * This file is the module file which contains the hook_cron
 */

use Guzzle\Http;
use Drupal\Component\Serialization\Json;


/**
 * Implements hook_cron().
 */
function suchi_blocks_cron() {

  // List all the blocks of the type stock_exchange_rate_card.
  $blocks =  \Drupal::entityTypeManager()
    ->getStorage('block_content')
    ->loadByProperties(array('type' => 'stock_exchange_rate_card'));

  foreach ($blocks AS $block) {
    $symbol = $block->field_symbol->value;

    // Make API call to get values of changed and last price.
    $return_from_API = _get_API_call($symbol);
    $last_price = $return_from_API->LastPrice;
    $change = $return_from_API->Change;

    // Now update the block with the values returned by the API.
    $block->field_last_price = $last_price;
    $block->field_change = $change;
    $block->save();
  }
}

/**
 * Helper function to send out calls to markitondemand and return back Last Prics and Change values
 * http://dev.markitondemand.com/MODApis/Api/v2/Quote/json?symbol=BAC&callback=myFunction
 * @param $symbol
 */
function _get_API_call($symbol){
  // Create the URL.
  $url = "http://dev.markitondemand.com/MODApis/Api/v2/Quote/json?symbol=" . $symbol . "&callback=myFunction";

  // Make the API Call
  $client = new GuzzleHttp\Client();
  $request = $client->get($url);
  $response = $request->getBody();
  $response_json = json_decode((string)$response);

  return $response_json;
}